### ISSUE TITLE
Suggestion: Add LS DR10 "Type" entry to DMOST files where applicable

### ISSUE THREAD

**Issue by willcerny** [marlageha/dmost#1]
In denser systems, the Tractor photometry from the Legacy Surveys can occasionally fit the wrong type of model to a given source: e.g., fitting Sersic profiles to objects that the spectra suggest are stars. This may be an unavoidable problem for the sake of the actual measurements (short of redoing the photometry), but it would be good to be aware of when stellar magnitudes may be less reliable. The easiest way to account for this would be to add the "Type" column from the Legacy Surveys catalogs to the DMOST files so that the user can see whether the appropriate type has been assigned.

A description of the types that get assigned include: https://www.legacysurvey.org/dr10/description/#morphological-classification

**Comment by marlageha** [comment]
done.
